// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"DucTran999/di-with-go/internal/domain/inbound"
	"DucTran999/di-with-go/internal/handler"
	"DucTran999/di-with-go/internal/repository"
	"DucTran999/di-with-go/internal/usecase"
)

// Injectors from wire.go:

func InitUserHandler() inbound.UserHandler {
	userRepositoryImpl := repository.NewUserRepository()
	userUseCaseImpl := usecase.NewUserUseCase(userRepositoryImpl)
	userHandler := handler.NewUserHandler(userUseCaseImpl)
	return userHandler
}
